export const validations = ['oneNumber', 'oneLowercase', 'oneUppercase', 'minLength'];

export const STRINGS = {
  CHECKBOX: 'checkbox',
  TEXT_CONFIRM: 'textConfirm',
  TEXT_LABEL: 'textLabel',
  TEXT_INFO: 'textInfo',
  RED_LINK: 'redLink',
  EMAIL: 'email',
  PASSWORD: 'password',
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  TEXT_VALIDATION: 'textValidation',
  TEXT_VALIDATION_ERROR: 'textValidationError',
  TEXT_VALIDATION_SUCCESS: 'textValidationSuccess',
  MANAGER: 'manager',
  MIN_LENGTH: 'minLength',
  ONE_NUMBER: 'oneNumber',
  ONE_UPPERCASE: 'oneUppercase',
  ONE_LOWERCASE: 'oneLowercase',
  FIRST_NAME_REQUIRED: 'isFirstNameRequired',
  LAST_NAME_REQUIRED: 'isLastNameRequired',
  EMAIL_REQUIRED: 'isEmailRequired',
  INCORRECT_FORMAT: 'incorrectFormat',
  PASSWORD_REQUIRED: 'isPasswordRequired',
  PASSWORD_NOT_VALID: 'passwordIsNotValid',
  TEXT_RESET: 'textReset',
  RESET_LINK: 'resetLink',
  FORGOT_PASS_LINK: 'forgotPassLink',
  TYPE_STRING: 'string',
  INPUT: 'INPUT',
  TEXT: 'text',
  NEW_PASSWORD: 'newPassword',
  CONFIRM_PASSWORD: 'confirmPassword',
  RESET_PASS_CONTAINER: 'resetPassContainer',
  DONT_MATCH: 'dontMatch',
  NEW_PASSWORD_REQUIRED: 'isNewPasswordRequired',
  CONFIRM_PASSWORD_REQUIRED: 'isConfirmPasswordRequired',
  MIN_PASSWORD_LENGTH: 8,
  FORGOT_ERROR: 'forgotError',
  RESET_ERROR: 'resetError',
  SIGNUP_ERROR: 'signUpError',
  LOGIN_ERROR: 'loginError',
};
